// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
)

type Order struct {
	ID            int32         `json:"id"`
	Userid        int32         `json:"userid"`
	Amount        sql.NullInt32 `json:"amount"`
	Accountnumber string        `json:"accountnumber"`
	Currency      string        `json:"currency"`
	Description   string        `json:"description"`
	Createdat     sql.NullTime  `json:"createdat"`
	Updatedat     sql.NullTime  `json:"updatedat"`
	Status        string        `json:"status"`
}
