CREATE TABLE Orders (
    ID INT NOT NULL AUTO_INCREMENT,
    UserId INT NOT NULL,
    Amount INT DEFAULT 0 CHECK (Amount > 0),
    AccountNumber VARCHAR(255) NOT NULL,
    Currency VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Status VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX idx_order_user ON Orders (UserId);